### PR TITLE
🔨 refactor ManageUser component

### PR DESCRIPTION
**Pull request by ozgunbal**
Related issue #58

### CODE REVIEW

**Review by razvanilin — APPROVED** [review]
Looks good, thanks!

**Comment by ozgunbal** [comment]
hi, @razvanilin . This year, Hacktoberfest wants to observe PR is eligible for 2 weeks after it's pushed when you don't labeled with `hacktoberfest-accepted`. You removed the repository's `hacktoberfest` label so this PR's didn't count right now. Can you help me on this.

**Comment by razvanilin** [comment]
@ozgunbal sorry, I had no idea removing the label has any secondary effect. I added both labels now, let me know if that did it. I will also merge this tomorrow or Thursday.

**Comment by ozgunbal** [comment]
I don't know what their rules are, but currently 2 PR of mine has tagged via ineligible repository. I'm posting you the rules, for double check: https://hacktoberfest.digitalocean.com/hacktoberfest-update

**Comment by razvanilin** [comment]
I sent an email to the Hacktoberfest team. I'll let you know if they manage to re-validate the PRs on their side

**Pull request merged**
